"""Setup wizard for Mully Mouth Golf Caddy configuration."""
import os
import sys
from pathlib import Path


def print_header(text: str) -> None:
    """Print formatted header."""
    print("\n" + "=" * 60)
    print(text.center(60))
    print("=" * 60 + "\n")


def get_input(prompt: str, default: str = "") -> str:
    """Get user input with optional default value."""
    if default:
        prompt += f" [{default}]"
    prompt += ": "

    value = input(prompt).strip()
    return value if value else default


def main() -> int:
    """Run setup wizard."""
    print_header("Mully Mouth Golf Caddy - Setup Wizard")

    print("Welcome! This wizard will help you configure Mully Mouth.")
    print("Press Ctrl+C at any time to exit.\n")

    try:
        # Step 1: API Keys
        print_header("Step 1: API Keys")

        print("You need two API keys to use Mully Mouth:")
        print("  1. Anthropic API key (for Claude AI)")
        print("  2. ElevenLabs API key (for voice synthesis)\n")

        print("Get your Anthropic API key at: https://console.anthropic.com/")
        anthropic_key = get_input("Enter your Anthropic API key")

        if not anthropic_key:
            print("\nError: Anthropic API key is required.")
            return 1

        print("\nGet your ElevenLabs API key at: https://elevenlabs.io/")
        elevenlabs_key = get_input("Enter your ElevenLabs API key")

        if not elevenlabs_key:
            print("\nError: ElevenLabs API key is required.")
            return 1

        # Step 2: Personality
        print_header("Step 2: Commentary Personality")

        print("Available personalities:")
        print("  1. neutral - Professional, informative")
        print("  2. sarcastic - Humorous, light-hearted ribbing")
        print("  3. encouraging - Supportive, motivational\n")

        personality_choice = get_input("Choose personality (1-3)", "1")

        personality_map = {
            "1": "neutral",
            "2": "sarcastic",
            "3": "encouraging",
        }

        personality = personality_map.get(personality_choice, "neutral")

        # Step 3: Voice Settings (optional)
        print_header("Step 3: Voice Settings (Optional)")

        print("You can customize voice settings or use defaults.")
        print("Default voice: Rachel (ElevenLabs ID: 21m00Tcm4TlvDq8ikWAM)\n")

        use_custom_voice = get_input("Customize voice settings? (y/n)", "n").lower()

        voice_id = "21m00Tcm4TlvDq8ikWAM"  # Default
        stability = "0.5"
        similarity = "0.75"

        if use_custom_voice == "y":
            voice_id = get_input("Voice ID", voice_id)
            stability = get_input("Stability (0.0-1.0)", stability)
            similarity = get_input("Similarity boost (0.0-1.0)", similarity)

        # Step 4: Motion Detection (optional)
        print_header("Step 4: Motion Detection (Optional)")

        print("Motion detection sensitivity can be adjusted.")
        print("Lower values = more sensitive (may detect false shots)")
        print("Higher values = less sensitive (may miss shots)\n")

        use_custom_motion = get_input("Customize motion settings? (y/n)", "n").lower()

        motion_threshold = "0.02"
        ball_stop_duration = "1.0"

        if use_custom_motion == "y":
            motion_threshold = get_input("Motion threshold (0.0-1.0)", motion_threshold)
            ball_stop_duration = get_input("Ball stop duration (seconds)", ball_stop_duration)

        # Step 5: Generate config file
        print_header("Step 5: Creating Configuration")

        config_content = f"""# Mully Mouth Configuration
# Generated by setup wizard

# Anthropic (Claude AI) Configuration
anthropic:
  api_key: {anthropic_key}
  model: claude-3-5-sonnet-20241022

# ElevenLabs (Voice) Configuration
elevenlabs:
  api_key: {elevenlabs_key}
  voice_id: {voice_id}
  model: eleven_monolingual_v1
  stability: {stability}
  similarity_boost: {similarity}

# Commentary Personality
personality: {personality}

# Monitoring Settings
monitoring:
  fps: 2
  motion_threshold: {motion_threshold}
  ball_stop_duration: {ball_stop_duration}

# Cache Settings
cache:
  pattern_cache_file: data/cache/pattern_cache.json
  hamming_threshold: 10
  min_confidence_to_cache: 0.7

# Cost Limits
cost:
  max_cost_per_round: 5.0
  warn_at_cost: 3.0

# Logging
logging:
  level: INFO
  file: logs/mully_mouth.log

# Hotkeys (optional)
hotkeys:
  toggle_voice: null
  force_analyze: null
  correction_mode: null
"""

        # Ensure config directory exists
        config_dir = Path("config")
        config_dir.mkdir(exist_ok=True)

        # Write config file
        config_file = config_dir / "config.yaml"
        with open(config_file, "w") as f:
            f.write(config_content)

        print(f"Configuration saved to: {config_file}")

        # Create data directories
        print("\nCreating data directories...")
        for dir_path in [
            "data/cache",
            "data/sessions",
            "data/training",
            "logs",
        ]:
            Path(dir_path).mkdir(parents=True, exist_ok=True)

        print("Data directories created.")

        # Success
        print_header("Setup Complete!")

        print("Mully Mouth is now configured and ready to use.")
        print("\nTo start using Mully Mouth:")
        print("  1. Launch GS Pro")
        print(f"  2. Run: python -m src.cli.main")
        print(f"  3. Play golf - commentary will be generated automatically\n")

        print("For more options, run: python -m src.cli.main --help\n")

        return 0

    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        return 1
    except Exception as e:
        print(f"\nError during setup: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
